### ISSUE TITLE
How to hide tab bar item n react-navigation

### ISSUE THREAD

**Issue by nihp** [react-navigation/rfcs#81]
Any option to hide the tab bar item in react-navigation?

showTab option is supported or not?

**Comment by sapjax** [comment]
tabBarButtonComponent: null

**Comment by nihp** [comment]
tabBarButtonComponent: null

@sapjax This not worked for me

**Comment by satya164** [comment]
This repo is meant for discussions and proposals. Please don't open support requests here,
